
import { Agent, AgentCategory } from './types';

// Exporting TAG_DESCRIPTIONS to provide tooltips for agent tags
export const TAG_DESCRIPTIONS: Record<string, string> = {
  'terminal': 'Built for the command line environment.',
  'open-source': 'Code is publicly available and community-driven.',
  'productivity': 'Designed to speed up development workflows.',
  'rust': 'Built using the high-performance Rust programming language.',
  'proprietary': 'Closed-source tool with managed features.',
  'coding': 'Specialized for software engineering tasks.',
  'autonomous': 'Capable of executing multi-step tasks independently.',
  'sota': 'State-of-the-art model or architecture.',
  'git': 'Deep integration with Git version control.',
  'python': 'Powered by or built with Python.',
  'go': 'Built with the Go programming language.',
  'complex-tasks': 'Optimized for long-running, multi-file operations.',
  'planning': 'Features advanced strategy and task breakdown.',
  'security': 'Focuses on safe execution and data protection.',
  'sandbox': 'Executes code in isolated environments.',
  'github': 'Part of the GitHub ecosystem.',
  'official': 'Maintained by the original service provider.',
  'aws': 'Optimized for Amazon Web Services.',
  'cloud': 'Cloud-native architecture and scaling.',
  'google': 'Built by Google or leverages Google AI.',
  'utility': 'A focused tool for specific CLI operations.',
  'local-llm': 'Runs Large Language Models on local hardware.',
  'inference': 'Focused on high-speed model execution.',
  'gui': 'Features a graphical user interface component.',
  'api': 'Provides a programmable interface for integrations.',
  'distributed': 'Supports multi-node or P2P operations.',
  'privacy': 'Designed to protect user data and local processing.',
  'offline': 'Works without an internet connection.',
  'desktop': 'A standalone application for desktop OS.',
  'mozilla': 'Maintained by the Mozilla Foundation.',
  'foundational': 'Base tool for other agents or frameworks.',
  'portable': 'Runs as a single executable without dependencies.',
  'automation': 'Automates repetitive system tasks.',
  'interpreter': 'Directly executes code in various languages.',
  'bash': 'Enhanced shell script generation.',
  'snippets': 'Manages reusable code segments.',
  'prompts': 'Uses curated prompt engineering patterns.',
  'framework': 'A building block for creating other agents.',
  'debugging': 'Aids in finding and fixing code errors.',
  'logging': 'Detailed tracking of model interactions.',
  'experimentation': 'Ideal for testing different models or prompts.',
  'iac': 'Infrastructure as Code automation.',
  'tui': 'Terminal User Interface with visual elements.'
};

export const AGENTS: Agent[] = [
  // --- 2.0 AI-ENHANCED TERMINAL EMULATORS ---
  {
    id: 'wave-terminal',
    name: 'Wave Terminal',
    description: 'Open-source, IDE-like terminal with graphical widgets and block-based output.',
    longDescription: 'Wave Terminal brings a rich, IDE-like experience to the command line. It features an inline web browser, markdown previews, and command blocks that isolate execution steps for agentic oversight.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 12500,
    language: 'TypeScript',
    installCommand: 'brew install --cask waveterm',
    repoUrl: 'https://github.com/wavetermdev/waveterm',
    features: ['Integrated AI Chat', 'Built-in Editor', 'Command Blocks', 'Inline Multimedia'],
    tags: ['terminal', 'open-source', 'productivity'],
    useCases: ['Monitoring agent execution plans.', 'Editing remote files.', 'In-terminal documentation browsing.'],
    reviews: [],
    version: 'v0.7.2'
  },
  {
    id: 'warp',
    name: 'Warp',
    description: 'Rust-based terminal purpose-built for AI-powered collaboration.',
    longDescription: 'Warp is an agentic development environment that unifies tooling across the software lifecycle. It features native agentic workflows and an integrated code review interface.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 21000,
    language: 'Rust',
    installCommand: 'brew install --cask warp',
    repoUrl: 'https://www.warp.dev/',
    features: ['Agentic Workflow Integration', 'Warp Drive Collaboration', 'Block-based outputs'],
    tags: ['terminal', 'rust', 'proprietary'],
    useCases: ['Translating intent to bash.', 'Collaborative debugging.', 'Team-shared terminal blocks.'],
    reviews: [],
    version: '2025.01.12'
  },
  // --- 3.0 AGENTIC CODING ASSISTANTS ---
  {
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Anthropic\'s command-line tool for agentic software engineering.',
    longDescription: 'Powered by Claude 3.7 Sonnet, it delegates tasks like bug fixes and feature implementation autonomously using BashTool and FileEditTool.',
    category: AgentCategory.AUTONOMOUS,
    stars: 18000,
    language: 'TypeScript',
    installCommand: 'npm install -g @anthropic-ai/claude-code',
    repoUrl: 'https://github.com/anthropic/claude-code',
    features: ['Context Building', 'BashTool execution', 'Tiered Permissions'],
    tags: ['coding', 'autonomous', 'sota'],
    useCases: ['Complex refactoring.', 'Autonomous bug detection.', 'CI/CD pipeline automation.'],
    reviews: [],
    version: 'v1.0.4'
  },
  {
    id: 'cline',
    name: 'Cline',
    description: 'Open-source coding agent with a methodical Plan & Act workflow.',
    longDescription: 'Distinguished by its separation of strategy and implementation. Features Memory Bank system and Checkpoint management for immutable snapshots.',
    category: AgentCategory.CODING,
    stars: 11500,
    language: 'TypeScript',
    installCommand: 'npm install -g cline',
    repoUrl: 'https://github.com/cline/cline',
    features: ['Memory Bank', 'Plan & Act workflow', 'Checkpoint snapshots'],
    tags: ['open-source', 'coding', 'git'],
    useCases: ['Safe experimentation with snapshots.', 'Local-first private coding.', 'Methodical feature planning.'],
    reviews: [],
    version: 'v2.1.0'
  },
  {
    id: 'aider',
    name: 'Aider',
    description: 'CLI chat tool for pair programming with deep Git integration.',
    longDescription: 'Aider builds a map of the local repository and works seamlessly with Git history to review, amend, and commit changes autonomously.',
    category: AgentCategory.CODING,
    stars: 16000,
    language: 'Python',
    installCommand: 'pip install aider-chat',
    repoUrl: 'https://github.com/paul-gauthier/aider',
    features: ['Repository Mapping', 'Deep Git Integration', 'Multi-LLM Support'],
    tags: ['python', 'git', 'coding'],
    useCases: ['Large module refactoring.', 'Managing project-wide code changes.', 'Git conflict resolution.'],
    reviews: [],
    version: 'v0.68.0'
  },
  {
    id: 'plandex',
    name: 'Plandex',
    description: 'Engineered for massive coding tasks and 2M token context windows.',
    longDescription: 'Plandex manages complex, multi-step tasks across large codebases using tree-sitter indexing and intelligent context caching.',
    category: AgentCategory.CODING,
    stars: 7500,
    language: 'Go',
    installCommand: 'curl -sL https://plandex.ai/install.sh | bash',
    repoUrl: 'https://github.com/plandex-ai/plandex',
    features: ['2M Context window', 'Automated Debugging', 'Tree-sitter indexing'],
    tags: ['go', 'complex-tasks', 'planning'],
    useCases: ['Enterprise-scale codebase navigation.', 'Long-running multi-file implementation.', 'Automated test suite debugging.'],
    reviews: [],
    version: 'v0.12.0'
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    description: 'Security-first autonomous engineering with native sandboxing.',
    longDescription: 'Provides an isolated environment for agents to operate safely, preventing unintended system changes during autonomous development.',
    category: AgentCategory.AUTONOMOUS,
    stars: 25000,
    language: 'Python',
    installCommand: 'docker run -it ghcr.io/all-hands-ai/openhands',
    repoUrl: 'https://github.com/All-Hands-AI/OpenHands',
    features: ['Native Sandboxing', 'Model-Agnostic', 'Secure Isolation'],
    tags: ['python', 'security', 'sandbox'],
    useCases: ['Safe execution of untrusted scripts.', 'Sandboxed feature building.', 'Security analysis of code.'],
    reviews: [],
    version: 'v0.15.2'
  },
  {
    id: 'gh-copilot',
    name: 'GitHub Copilot Agent',
    description: 'Autonomous workspace partner within the GitHub ecosystem.',
    longDescription: 'The Agent mode in GitHub Copilot autonomously finds context across workspaces, edits multiple files, and runs terminal commands to completion.',
    category: AgentCategory.CODING,
    stars: 15000,
    language: 'Go',
    installCommand: 'gh extension install github/gh-copilot',
    repoUrl: 'https://github.com/github/gh-copilot',
    features: ['Agent Mode Activation', 'Official Workspace Indexing', 'Multi-file Edits'],
    tags: ['github', 'official', 'productivity'],
    useCases: ['Automating PR reviews.', 'Complex workspace navigation.', 'Iterative feature development.'],
    reviews: [],
    version: 'v1.2.0'
  },
  {
    id: 'amazon-q',
    name: 'Amazon Q CLI',
    description: 'AWS-native AI assistant with type-ahead shell completions.',
    longDescription: 'Integrates chat and autocompletion directly into the shell, providing ghost text suggestions for aws, git, npm, and docker.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 3000,
    language: 'Go',
    installCommand: 'brew install amazon-q',
    repoUrl: 'https://aws.amazon.com/q/',
    features: ['Ghost Text Suggestions', 'Intelligent completions', 'AWS native optimization'],
    tags: ['aws', 'cloud', 'productivity'],
    useCases: ['Accelerating AWS deployments.', 'Learning complex CLI flags.', 'Faster terminal navigation.'],
    reviews: [],
    version: '2025.1'
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    description: 'Terminal agent leveraging Google\'s 1M context window models.',
    longDescription: 'A high-context terminal tool optimized for reasoning over extensive codebases and documentation sets using Gemini 1.5/2.0.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 10000,
    language: 'Python',
    installCommand: 'pip install gemini-chat-cli',
    repoUrl: 'https://github.com/google/gemini-cli',
    features: ['1M Context support', 'Native Tool Integration', 'Google Cloud backend'],
    tags: ['google', 'sota', 'utility'],
    useCases: ['Analyzing massive documentation.', 'Fast coding queries.', 'Large-scale repo summarization.'],
    reviews: [],
    version: 'v1.4.0'
  },
  // --- 4.0 LOCAL FRAMEWORKS ---
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'The industry standard for running open LLMs locally.',
    longDescription: 'Built on llama.cpp, it provides high-throughput performance with broad hardware acceleration across NVIDIA, Apple, and AMD GPUs.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 75000,
    language: 'Go',
    installCommand: 'curl -fsSL https://ollama.com/install.sh | sh',
    repoUrl: 'https://ollama.com/',
    features: ['Hardware acceleration', 'Stable tool calling', 'REST API'],
    tags: ['local-llm', 'open-source', 'inference'],
    useCases: ['Private AI serving.', 'Local agent hosting.', 'Offline development.'],
    reviews: [],
    version: 'v0.5.7'
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    description: 'Polished desktop interface for managing local models.',
    longDescription: 'Offers the most accessible graphical interface for discovering and running models from Hugging Face with an OpenAI-compatible API server.',
    category: AgentCategory.RESEARCH,
    stars: 32000,
    language: 'C++',
    installCommand: 'brew install --cask lm-studio',
    repoUrl: 'https://lmstudio.ai/',
    features: ['Hugging Face integration', 'Visual parameter tuning', 'Local server'],
    tags: ['local-llm', 'gui', 'inference'],
    useCases: ['Visual model benchmarking.', 'Prototyping local agent flows.', 'Low-barrier entry to local AI.'],
    reviews: [],
    version: 'v0.3.5'
  },
  {
    id: 'localai',
    name: 'LocalAI',
    description: 'Drop-in open-source replacement for the OpenAI API.',
    longDescription: 'Supports text, image, and audio generation locally with production-ready tool calling and P2P distributed inference.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 22000,
    language: 'Go',
    installCommand: 'docker run -p 8080:8080 localai/localai',
    repoUrl: 'https://localai.io/',
    features: ['P2P Inference', 'Function calling', 'Multi-modal'],
    tags: ['local-llm', 'api', 'distributed'],
    useCases: ['Enterprise self-hosting.', 'Building tool-using agents locally.', 'Secure on-prem AI stacks.'],
    reviews: [],
    version: 'v2.24.0'
  },
  {
    id: 'jan',
    name: 'Jan',
    description: 'Privacy-focused offline ChatGPT alternative.',
    longDescription: 'A comprehensive, 100% offline AI chat experience powered by the Cortex engine for local device execution.',
    category: AgentCategory.RESEARCH,
    stars: 15000,
    language: 'TypeScript',
    installCommand: 'brew install --cask jan',
    repoUrl: 'https://jan.ai/',
    features: ['Cortex Engine', '100% Offline', 'Extensions'],
    tags: ['privacy', 'offline', 'desktop'],
    useCases: ['Air-gapped AI chat.', 'Private document analysis.', 'Personal knowledge management.'],
    reviews: [],
    version: 'v0.5.8'
  },
  {
    id: 'llamafile',
    name: 'Llamafile',
    description: 'Single-executable distribution for Large Language Models.',
    longDescription: 'Mozilla-backed project that packages weights and inference engines into a single multi-platform executable file.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 17000,
    language: 'C++',
    installCommand: 'wget ... && chmod +x ...',
    repoUrl: 'https://github.com/Mozilla-Ocho/llamafile',
    features: ['Zero installation', 'Single-executable', 'Multi-platform'],
    tags: ['mozilla', 'foundational', 'portable'],
    useCases: ['Portable AI on thumb drives.', 'Simple model distribution.', 'Zero-dependency deployments.'],
    reviews: [],
    version: 'v0.8.1'
  },
  // --- 5.0 SPECIALIZED AUTOMATION ---
  {
    id: 'open-interpreter',
    name: 'Open Interpreter',
    description: 'Natural language interface for full system control.',
    longDescription: 'Executes code (Python, JS, Shell) locally with unrestricted internet and file access for general-purpose automation.',
    category: AgentCategory.AUTONOMOUS,
    stars: 52000,
    language: 'Python',
    installCommand: 'pip install open-interpreter',
    repoUrl: 'https://openinterpreter.com/',
    features: ['OS Control', 'Local Execution', 'Vision support'],
    tags: ['automation', 'interpreter', 'local'],
    useCases: ['Complex desktop automation.', 'Programmatic file analysis.', 'Autonomous research.'],
    reviews: [],
    version: 'v0.2.0'
  },
  {
    id: 'shell-gpt',
    name: 'ShellGPT (sgpt)',
    description: 'Shell productivity tool for generating commands and snippets.',
    longDescription: 'Translates natural language into executable bash commands directly in the terminal. Optimized for shell productivity.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 11000,
    language: 'Python',
    installCommand: 'pip install shell-gpt',
    repoUrl: 'https://github.com/TheR1D/shell_gpt',
    features: ['REPL mode', 'Shell snippets', 'Custom functions'],
    tags: ['bash', 'productivity', 'snippets'],
    useCases: ['Translating intent to regex/ffmpeg.', 'Quick terminal lookup.', 'Interactive terminal chat.'],
    reviews: [],
    version: 'v0.9.1'
  },
  {
    id: 'fabric',
    name: 'Fabric',
    description: 'Framework for applying crowdsourced prompt patterns to terminal tasks.',
    longDescription: 'Organizes tested prompt patterns for high-quality technical extraction and summarization in the CLI.',
    category: AgentCategory.RESEARCH,
    stars: 18000,
    language: 'Go',
    installCommand: 'go install github.com/danielmiessler/fabric@latest',
    repoUrl: 'https://github.com/danielmiessler/fabric',
    features: ['Pattern Library', 'Consistent outputs', 'Summarization'],
    tags: ['prompts', 'productivity', 'framework'],
    useCases: ['Technical transcription extraction.', 'Structured article summaries.', 'Pattern-based automation.'],
    reviews: [],
    version: 'v2.1'
  },
  {
    id: 'ask-sh',
    name: 'ask.sh',
    description: 'Terminal assistant that reads/writes directly to the shell session.',
    longDescription: 'Eliminates copy-pasting by reading the terminal buffer to understand error context and injecting fixes directly.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 3500,
    language: 'Rust',
    installCommand: 'brew install ask-sh',
    repoUrl: 'https://github.com/todo/ask-sh',
    features: ['Buffer reading', 'Direct injection', 'Context awareness'],
    tags: ['rust', 'debugging', 'productivity'],
    useCases: ['Instant debugging of terminal errors.', 'Command auto-correction.', 'Fast tool navigation.'],
    reviews: [],
    version: 'v0.4.0'
  },
  {
    id: 'llm-cli',
    name: 'LLM (Simon Willison)',
    description: 'Swiss-army knife for prompting dozens of models from the CLI.',
    longDescription: 'A versatile utility for prompting and model interaction. Logs all interactions to SQLite for historical reference.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 8000,
    language: 'Python',
    installCommand: 'pip install llm',
    repoUrl: 'https://llm.datasette.io/',
    features: ['Plugin system', 'SQLite logging', 'Multi-model support'],
    tags: ['python', 'logging', 'experimentation'],
    useCases: ['Benchmarking different prompts.', 'Scripting AI interactions.', 'Preserving conversation history.'],
    reviews: [],
    version: 'v0.18'
  },
  // --- 6.0 FOUNDATIONAL TOOLS ---
  {
    id: 'aws-cli',
    name: 'AWS CLI',
    description: 'Official tool for managing Amazon Web Services resources.',
    longDescription: 'The foundational command-line instrument for cloud management and infrastructure orchestration.',
    category: AgentCategory.INFRASTRUCTURE,
    stars: 16000,
    language: 'Python',
    installCommand: 'brew install awscli',
    repoUrl: 'https://aws.amazon.com/cli/',
    features: ['Comprehensive coverage', 'Automation ready', 'Consistent syntax'],
    tags: ['aws', 'cloud', 'foundational'],
    useCases: ['Infrastructure automation.', 'Managing S3/EC2 via scripts.', 'CI/CD pipeline integration.'],
    reviews: [],
    version: 'v2.17'
  },
  {
    id: 'pulstack',
    name: 'Pulstack',
    description: 'Deploys static websites to AWS/GitHub with zero manual work.',
    longDescription: 'Uses Pulumi to provision secure-by-default infrastructure for static sites automatically.',
    category: AgentCategory.INFRASTRUCTURE,
    stars: 2500,
    language: 'Go',
    installCommand: 'npm install -g pulstack',
    repoUrl: 'https://github.com/todo/pulstack',
    features: ['Secure by default', 'Zero manual work', 'IaC native'],
    tags: ['iac', 'aws', 'automation'],
    useCases: ['Rapid static site hosting.', 'Secure cloud provisioning.', 'Automatic site teardown.'],
    reviews: [],
    version: 'v1.0.2'
  },
  {
    id: 'lazygit',
    name: 'Lazygit',
    description: 'Intuitive terminal user interface for Git commands.',
    longDescription: 'Simplifies complex Git operations like interactive staging and squashing into an efficient TUI.',
    category: AgentCategory.TERMINAL_UTILITY,
    stars: 48000,
    language: 'Go',
    installCommand: 'brew install lazygit',
    repoUrl: 'https://github.com/jesseduffield/lazygit',
    features: ['Interactive staging', 'Commit squashing', 'Visual diffs'],
    tags: ['git', 'tui', 'go'],
    useCases: ['Speeding up Git workflows.', 'Complex conflict resolution.', 'Visual Git navigation.'],
    reviews: [],
    version: 'v0.40'
  }
];

export const MOCK_HISTORY = [
  { year: 2005, event: 'Git Created', detail: 'Foundational version control system.' },
  { year: 2022, event: 'AI Explosion', detail: 'LLMs begin redefining terminal interaction.' },
  { year: 2024, event: 'Autonomous Agents', detail: 'Tools like Aider and Claude Code take center stage.' },
  { year: 2025, event: 'Agentic CLI Era', detail: 'Terminal evolves into an autonomous dev environment.' },
];
